### PR TITLE
Fix typescript typing from add namespace for stable

### PR DESCRIPTION
**Pull request by corbinu**
The new typing has a compile error this corrects it. Thanks!

### CODE REVIEW

**Comment by BridgeAR** [comment]
@corbinu thanks a lot! It would indeed be great to have a test for this. And suggestion on that?

@mcollina I think we should go ahead and land this right now, no matter that it would be great to have a test for it!

**Comment by davidmarkclements** [comment]
2.0.2 npm pub'd

**Comment by corbinu** [comment]
@BridgeAR Will add! and @davidmarkclements Thanks!

**Comment by corbinu** [comment]
@BridgeAR @davidmarkclements Would you mind if I restructure things to have a test dir that way we have a stable, regular and typescript test? Unless your willing to just let me rewrite the tests in TypeScript ;)

**Comment by davidmarkclements** [comment]
hahaha feel free to create a test dir – I'll pass on the TS for tests :rofl:

**Pull request merged**
